### ISSUE TITLE
[alpha testing] Sign Up

### ISSUE THREAD

**Issue by ulgal** [swsnu/swpp2019-team18#35]
첫 페이지에서 Sign Up이 네모로 감싸져있어서 버튼처럼 생각했는데, Sign Up 글자에 링크가 걸려있네요. 단순히 글만 있거나, 네모 전체를 링크로 걸어주는게 좋지 않을까 생각합니다..

그리고 Login이 안된 경우 Login 페이지로 가도록 한 것 같은데, Signup 페이지에서도 새로고침 시 Login 페이지로 갑니다.

**Comment by mmsori** [comment]
피드백 감사합니다 수정하겠습니다!
