### ISSUE TITLE
[alpha testing] tag filtering on garden page is not working

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team18#42]
<img width="1440" alt="스크린샷 2019-12-05 오후 7 14 46" src="https://user-images.githubusercontent.com/17784659/70226088-8a87ac00-1793-11ea-921c-f7945d246a0c.png">

<img width="1440" alt="스크린샷 2019-12-05 오후 7 12 32" src="https://user-images.githubusercontent.com/17784659/70225966-5ca26780-1793-11ea-9004-deef97ba20de.png">

게시글 중에 `SPORTS`가 있어서 표시되어야 할 것 같은데, 표시되지 않습니다.

**Comment by gywls00** [comment]
저희가 sport 와 sports를 혼동해서 사용되서 load가 안된 것 같습니다
sport로 통일하겠습니다!
