### ISSUE TITLE
[alpha testing] searching people on create page

### ISSUE THREAD

**Issue by coffeetea99** [swsnu/swpp2019-team18#46]
Create page에서 people 칸에 뭐라고 적고 다른 칸을 누르면 적은 게 지워집니다

**Comment by mmsori** [comment]
다이어리 작성 화면에서 add people을 통해 사람을 먼저 추가하는 작업이 선행되어야 합니다. add people을 통해  다른 일기를 쓸 때도 people칸에 태그할 수 있습니다.
