### ISSUE TITLE
[Alpha Testing] 이름이 같은 유저 등록

### ISSUE THREAD

**Issue by nungnung** [swsnu/swpp2019-team18#49]
친구 추가에서 이름이 같은 친구를 등록하는 것이 허용되어 있는데,
나중에 찾을 때 구별하기 어려운 것 같아요.

**Comment by mmsori** [comment]
동명이인을 information으로 구분하는 것이 본래 의도였으나,  일기 작성 과정에서는 information 정보를 따로 주지 않기 때문에 말씀주신 문제가 발생할 것 같습니다. 피드백 감사드리며 개선하도록 하겠습니다!

**Comment by yunsu3042** [comment]
검색시 툴팁을 통해서 추가 정보를 보여주는 방식으로 선택하도록 할 예정입니다.
